// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-MfHPuDSuYlgUN_w47dbu4RVYz3bnqS4',
    appId: '1:927552932609:web:4ac9bd56db275e1f2da900',
    messagingSenderId: '927552932609',
    projectId: 'reddit-clone-34c09',
    authDomain: 'reddit-clone-34c09.firebaseapp.com',
    storageBucket: 'reddit-clone-34c09.appspot.com',
    measurementId: 'G-V2FWXS9TB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyTFhA5lJ6Em0Z7XziL7My_bvPTRxL68k',
    appId: '1:927552932609:android:d700796ba3ec8f0f2da900',
    messagingSenderId: '927552932609',
    projectId: 'reddit-clone-34c09',
    storageBucket: 'reddit-clone-34c09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTr71xBiwCJ2k1gX8_Hy3G9eO7HtMedew',
    appId: '1:927552932609:ios:592997232d7bcf092da900',
    messagingSenderId: '927552932609',
    projectId: 'reddit-clone-34c09',
    storageBucket: 'reddit-clone-34c09.appspot.com',
    iosClientId: '927552932609-p8sc4j2sbubmcb0djeprakgraneovm0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTr71xBiwCJ2k1gX8_Hy3G9eO7HtMedew',
    appId: '1:927552932609:ios:592997232d7bcf092da900',
    messagingSenderId: '927552932609',
    projectId: 'reddit-clone-34c09',
    storageBucket: 'reddit-clone-34c09.appspot.com',
    iosClientId: '927552932609-p8sc4j2sbubmcb0djeprakgraneovm0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
